function ImportMesures()
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 13-Oct-2009 14:57:17

display ('Import des fichiers CSV ...');
% Import les données du train 1
% Données liées à l'accelaration avant
newData1 = importdata('acceleration_avant_01.csv');

% Affect les données.
assignin ('base', 'Courant_AV_A_01', newData1.data(:, 1));
assignin ('base', 'Position_AV_A_01', newData1.data(:, 2));
assignin ('base', 'Vitesse_AV_A_01', newData1.data(:, 3));

% Données liées au freinage avant
newData1 = importdata('freinage_avant_01.csv');

% Affect les données.
assignin ('base', 'Courant_AV_F_01', newData1.data(:, 1));
assignin ('base', 'Position_AV_F_01', newData1.data(:, 2));
assignin ('base', 'Vitesse_AV_F_01', newData1.data(:, 3));

% Données liées à l'accelaration arriere
newData1 = importdata('acceleration_arriere_01.csv');

% Affect les données.
assignin ('base', 'Courant_AR_A_01', newData1.data(:, 1));
assignin ('base', 'Position_AR_A_01', newData1.data(:, 2));
assignin ('base', 'Vitesse_AR_A_01', newData1.data(:, 3));

% Données liées au freinage arriere
newData1 = importdata('freinage_arriere_01.csv');

% Affect les données.
assignin ('base', 'Courant_AR_F_01', newData1.data(:, 1));
assignin ('base', 'Position_AR_F_01', newData1.data(:, 2));
assignin ('base', 'Vitesse_AR_F_01', newData1.data(:, 3));


% Import les données du train 2
% Données liées à l'accelaration avant
newData1 = importdata('acceleration_avant_02.csv');

% Affect les données.
assignin ('base', 'Courant_AV_A_02', newData1.data(:, 1));
assignin ('base', 'Position_AV_A_02', newData1.data(:, 2));
assignin ('base', 'Vitesse_AV_A_02', newData1.data(:, 3));

% Données liées au freinage avant
newData1 = importdata('freinage_avant_02.csv');

% Affect les données.
assignin ('base', 'Courant_AV_F_02', newData1.data(:, 1));
assignin ('base', 'Position_AV_F_02', newData1.data(:, 2));
assignin ('base', 'Vitesse_AV_F_02', newData1.data(:, 3));

% Données liées à l'accelaration arriere
newData1 = importdata('acceleration_arriere_02.csv');

% Affect les données.
assignin ('base', 'Courant_AR_A_02', newData1.data(:, 1));
assignin ('base', 'Position_AR_A_02', newData1.data(:, 2));
assignin ('base', 'Vitesse_AR_A_02', newData1.data(:, 3));

% Données liées au freinage arriere
newData1 = importdata('freinage_arriere_02.csv');

% Affect les données.
assignin ('base', 'Courant_AR_F_02', newData1.data(:, 1));
assignin ('base', 'Position_AR_F_02', newData1.data(:, 2));
assignin ('base', 'Vitesse_AR_F_02', newData1.data(:, 3));


% Import les données du train 3
% Données liées à l'accelaration avant
newData1 = importdata('acceleration_avant_03.csv');

% Affect les données.
assignin ('base', 'Courant_AV_A_03', newData1.data(:, 1));
assignin ('base', 'Position_AV_A_03', newData1.data(:, 2));
assignin ('base', 'Vitesse_AV_A_03', newData1.data(:, 3));

% Données liées au freinage avant
newData1 = importdata('freinage_avant_03.csv');

% Affect les données.
assignin ('base', 'Courant_AV_F_03', newData1.data(:, 1));
assignin ('base', 'Position_AV_F_03', newData1.data(:, 2));
assignin ('base', 'Vitesse_AV_F_03', newData1.data(:, 3));

% Données liées à l'accelaration arriere
newData1 = importdata('acceleration_arriere_03.csv');

% Affect les données.
assignin ('base', 'Courant_AR_A_03', newData1.data(:, 1));
assignin ('base', 'Position_AR_A_03', newData1.data(:, 2));
assignin ('base', 'Vitesse_AR_A_03', newData1.data(:, 3));

% Données liées au freinage arriere
newData1 = importdata('freinage_arriere_03.csv');

% Affect les données.
assignin ('base', 'Courant_AR_F_03', newData1.data(:, 1));
assignin ('base', 'Position_AR_F_03', newData1.data(:, 2));
assignin ('base', 'Vitesse_AR_F_03', newData1.data(:, 3));

Ecrete();
packTrain();




